# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!

target 'BMI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Google-Mobile-Ads-SDK', '~> 7.5'
  pod 'SwiftLint', '0.33.1', :configurations => ['Debug']

end
